FROM python:3.13-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir streamlit requests

COPY frontend_code/ ./frontend_code/

EXPOSE 8501

CMD ["streamlit", "run", "frontend_code/app.py", "--server.port=8501", "--server.address=0.0.0.0"]