import logging
import pickle
from datetime import date
from fastapi import APIRouter, Depends, HTTPException, status, BackgroundTasks

from backend_code.api_pydantic_schemas import (CourseRequest, DataBaseUser,
                                              UserCoursesResponse, CourseStatusResponse,
                                              DailyLessonResponse)
from backend_code.database import db_state
from backend_code.security import get_current_user
from backend_code.content_generator_code.pipeline_runner import run_pipeline

logging.basicConfig(
    format="%(asctime)s - %(levelname)s - %(name)s - %(message)s",
    datefmt="%Y:%m:%d %H:%M:%S",
    level=logging.INFO
)

logger=logging.getLogger(name="CourseRouter")
router=APIRouter(tags=["Courses"])

@router.post(path="/generate-course", status_code=status.HTTP_202_ACCEPTED)
async def generate_course(
    request: CourseRequest,
    background_tasks:BackgroundTasks,
    current_user: DataBaseUser=Depends(dependency=get_current_user)
):
    logger.info(msg=f"Course generation requested by {current_user.username} for topic: {request.topic}")
    background_tasks.add_task(
        func=run_pipeline,
        topic=request.topic,
        username=current_user.username,
        duration_months=request.duration_months,
        off_days=request.off_days,
        start_date=date.today()
        )
    return {
        "msg":f"Pipeline started for {request.topic}. Check MongoDB for updates",
        "requested_by": current_user.username
    }


@router.get(path="/my-courses", status_code=status.HTTP_200_OK, response_model=UserCoursesResponse)
async def get_user_courses(current_user: DataBaseUser=Depends(dependency=get_current_user)):
    """
    Lazy Load Endpoint: Retrieves a lightweight list of distinct courses generated by the logged-in user, including the overarching running project context, without loading heavy lesson contents.
    """

    logger.info(msg=f"Fetching high-level course dashboard summary for user: {current_user.username}")

    pipeline=[

        # Isolate documents belonging to the authenticated user
        {"$match":{
            "username":current_user.username
            }
        },

        # Sort the day number which will form as an inner key
        {"$sort": {
            "day_number":1
            }
        },

        # Group by unique topic title and capture the running project string 
        {"$group": {
            "_id" : "$course_topic",
            "running_use_case_project":{
                "$first":"$running_use_case_project"
                },
            "syllabus":{
                "$push": {
                    "day_number": "$day_number",
                    "daily_topic": "$daily_topic"
                    }
                }
            }
        },

        # Format output field names cleanly
        {
            "$project": {
                "_id":0,
                "course_topic": "$_id",
                "running_use_case_project":1,
                "syllabus":1
            }
        },

        # Sort alphabetically by course topic
        {"$sort": {
            "course_topic":1
            }
        }
    ]

    cursor=db_state.db.daily_lessons.aggregate(pipeline)
    courses=await cursor.to_list(length=None)

    return {
        "total_courses": len(courses),
        "courses": courses
    }


@router.get(path="/courses/{topic}", status_code=status.HTTP_200_OK)
async def get_course_by_topic(topic: str, current_user:DataBaseUser=Depends(dependency=get_current_user)):
    clean_topic=topic.replace("_"," ")
    cursor=db_state.db.daily_lessons.\
        find({'course_topic': clean_topic,'username':current_user.username}).\
            sort(key_or_list="day_number", direction=1)
    lessons=await cursor.to_list(length=None)

    if not lessons:
        logger.warning(f"No Lessons found for the topic: {clean_topic}")
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Course not found or has not started yet"
        )
    else:   
        for lesson in lessons:  lesson["_id"]=str(lesson["_id"])
    
    return {
        "course_topic": clean_topic,
        "total_lessons": len(lessons),
        "lessons": lessons
    }

@router.get(
    path="/courses/{topic}/status",
    status_code=status.HTTP_200_OK,
    response_model=CourseStatusResponse
)
async def get_generation_status(
    topic: str, 
    current_user: DataBaseUser=Depends(dependency=get_current_user)
):
    """
    Polling Endpoint: Allows the Streamlit UI to check the live background progress of course generation
    """
    logger.info(msg=f"Status poll requested by {current_user.username} for topic: {topic}")

    clean_topic=topic.replace("_"," ")
    thread_topic=topic.replace(" ","_")
    thread_id=f"course_generation_{current_user.username}_{thread_topic}"

    # Inspect Langgraph's internal checkpoints collection for active thread metadata
    checkpoint_doc=await db_state.db['checkpoints'].find_one(
        filter={"thread_id":thread_id},
        sort=[("checkpoint_id",-1)]
    )

    day_number=0
    total_study_days=0
    pending_tasks=[]

    # safely unpack the stored binary bson payload using pickle
    if checkpoint_doc and "checkpoint" in checkpoint_doc:
        raw_binary=checkpoint_doc['checkpoint']
        try:
            # Unpack the serialized graph state dictionary
            checkpoint_data=pickle.loads(raw_binary)
            
            pending_tasks=checkpoint_data.get("pending_sends",[])
            channel_values=checkpoint_data.get("channel_values",{})
            
            day_number=channel_values.get("day_number",0)
            total_study_days=channel_values.get("total_study_days",0)
            
        except Exception as e:
            logger.error(msg=f"Failed to unpickle binary checkpoint payload for {thread_id}: {e}")

    # Verify actual finalized progress by counting documents written to the daily_lessons collection
    completed_days_count=await db_state.db.daily_lessons.count_documents(
        filter={"course_topic": clean_topic, "username": current_user.username}
    )

    active_day=max(day_number,completed_days_count)

    is_finished=False
    if checkpoint_doc:
        is_finished=(total_study_days>0 and completed_days_count>=total_study_days) or ( len(pending_tasks)==0 and completed_days_count>0)
        status_str="COMPLETED" if is_finished else "IN_PROGRESS"
    elif completed_days_count==0:
        status_str="NOT_STARTED"
    elif completed_days_count>0:
        # Fallback if checkpoint doc is expired/missing but written DB modules exists
        status_str="COMPLETED"
        is_finished=True 
        
    return CourseStatusResponse(
        status=status_str,
        current_day=active_day,
        total_study_days=total_study_days,
        is_completed=is_finished
    )


@router.get(
    path="/courses/{topic}/day/{day_number}",
    status_code=status.HTTP_200_OK,
    response_model=DailyLessonResponse
)
async def get_lesson_deep_dive(
        topic: str, 
        day_number: int,
        current_user: DataBaseUser=Depends(dependency=get_current_user)
):
    """
    Granular Load Endpoint: Fetches detailed markdown payload anb training quiz strictly on-demand when clicked in the streamlit UI. 
    """
    logger.info(msg=f"Fetching granular module content for {topic}, Day {day_number}")

    clean_topic=topic.replace("_"," ")

    lesson=await db_state.db.daily_lessons.find_one(
        filter={
        "course_topic": clean_topic,
        "username": current_user.username,
        "day_number": day_number
    })

    if not lesson:
        logger.warning(msg=f"Module content missing for {clean_topic} Day {day_number}")
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Content for Day {day_number} is not available yet"
        )
    else:
        return DailyLessonResponse(
            course_topic=lesson.get("course_topic", clean_topic),
            running_use_case_project=lesson.get("running_use_case_project"),
            day_number=lesson.get("day_number",day_number),
            daily_topic=lesson.get("daily_topic","Untitled Module"),
            lesson_content=lesson.get("lesson_content"),
            quiz_content=lesson.get("quiz_content")
        )   
