import os
import logging
from datetime import date
from dotenv import load_dotenv
from asyncio import create_task

# Import the MCP Server SDK
from mcp.server.fastmcp import FastMCP
from motor.motor_asyncio import AsyncIOMotorClient

# Importing the actual business logic
from backend_code.content_generator_code.pipeline_runner import run_pipeline
from backend_code.database import db_state

load_dotenv()

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger=logging.getLogger(name="CourseGeneratorMCP")

# Initialize the MCP Server
mcp=FastMCP(name="CourseGeneratorServer")

MCP_IDENTITY=os.environ.get("MCP_USER","default_mcp_user")

def get_mcp_db():
    """
    Singleton connection manager for the MCP Server
    Ensures only ONE connection pool is opened and shared across all tools and background tasks.
    """
    if db_state.db is None:
        logger.info(msg="Initializing persistent Mongodb Connection for MCP Server...")
        mongo_uri=os.environ.get('MONGO_URI')
        db_state.client=AsyncIOMotorClient(host=mongo_uri)
        db_state.db=db_state.client.ai_course_generator
    return db_state

async def background_pipeline_worker(
        topic: str,
        username: str,
        duration_months: float,
        off_days: list[str]
    ):
    """
    Runs the heavy Langgraph Pipeline in the background and manages its own isolated MongoDB connection
    """
    logger.info(msg=f"Background Worker Started for topic: {topic}")
    get_mcp_db()
    try:
        await run_pipeline(
            topic=topic,
            username=username,
            duration_months=duration_months,
            off_days=off_days,
            start_date=date.today()
        )
    except Exception as e:
        logger.error(msg=f"Pipeline failed: {e}",exc_info=True)
        return f"Error: Failed to generate course. {str(e)}"

active_tasks=set()
# Generate new course
@mcp.tool()
async def generate_new_course(topic: str, duration_months: float, off_days: list[str]) ->str:
    """
    Triggers the AI Agent pipeline to research and generate a comprehensive daily study course.
    Use this tool ONLY when the user explicitly asks to generate, create, or bild a NEW course syllabus.

    Args:
        topic: The main subject the user wants to learn (e.g., "Advanced Python")
        duration_months: How long the course should last in months (e.g., 1.5).
        off_days: A list of days of the week to take off (e.g.: ["Sunday","Wednesday"])
    """
    logger.info(f"LLM requested to generate course for: {topic}")

    task=create_task(coro=background_pipeline_worker(
        topic=topic,
        username=MCP_IDENTITY,
        duration_months=duration_months,
        off_days=off_days
    ))

  
    active_tasks.add(task)

    # tell the task to automatically remove itself from the set when it finishes
    task.add_done_callback(active_tasks.discard)


    # Immediately return a success message so that Claude does not time out
    return (
        f"""
        Successfully started generating the course for {topic} in the background! 
        It will take a few minutes to complete. Please advise the user to check back shortly by asking you to fetch the course summary.
        """
    )


# Read an existing course
@mcp.tool()
async def get_course_summary(topic: str) -> str:
    """
    Fetches an existing course curriculum from the MongoDB database
    Use this tool when the user asks to view, read, summarize or check if a course already exists.

    Args:
        topic: The exact name of the course to retrieve
    """
    logger.info(msg=f"LLM requested summary for existing course: {topic}")
    try:
        db=get_mcp_db()

        clean_topic=topic.replace("_"," ")
        cursor=db.db.daily_lessons.\
            find(filter={'course_topic':clean_topic,"username":MCP_IDENTITY}).\
                sort("day_number",1)
        lessons=await cursor.to_list(length=180)
        

        if not lessons:
            return f"No course found for the topic {topic}. You should ask the user if they would want to generate it."
        else:
            summary=f"Course: {clean_topic}\n Total Lessons Found: {len(lessons)} \n\n"
            for lesson in lessons[:5]: # return only the first 5 days
                summary+=f"Day {lesson['day_number']}: {lesson['daily_topic']}\n"
            summary+="\n...(More lessons are available in the database)"
            return summary
    except Exception as e:
        return f"Database Error: {str(e)}"
    

# List all user courses (Dashboard Context tool)
@mcp.tool()
async def list_user_courses() -> str:
    """
    Lists all distinct courses generated by the current user, including their overarching running project descriptions.
    Use this tool proactively to see what topics and practical projects the user is currently studying
    """
    logger.info(msg=f"LLM requested full course list for user: {MCP_IDENTITY}")
    try:
        db=get_mcp_db()

        pipeline=[
            {"$match":{"username":MCP_IDENTITY}},
            {"$sort": {"day_number":1}},
            {"$group": {
                "_id":"$course_topic",
                "running_use_case_project": {
                    "$first": "$running_use_case_project"                    
                    },
                "total_days": {"$sum": 1}
                } 
            },
            {"$sort": {"_id":1}}
        ]

        cursor=db.db.daily_lessons.aggregate(pipeline)
        courses=await cursor.to_list(length=None)

        if not courses:
            return "The user has not generated any courses yet. Offer to help them plan their first course"
        else:
            response="** Active User Curriculum Dashboard: **\n\n"
            for c in courses:
                project=c.get('running_use_case_project',"No Project specified")
                response+=f"- **Course Topic**: {c['_id']} \n - **Duration**: {c['total_days']} study days\n - **Overarching Project** {project}\n\n"
            return response

    except Exception as e:
        return f"Database Error while listing courses: {str(e)}"
    

@mcp.tool()
async def get_lesson_deep_dive(topic: str, day_number: int) -> str:
    """
    Retrieves the complete, unabridged lesson material and refresher assessment quiz for a specific course topic and study day. 
    Use this tool when acting as an interactive tutor to teach concepts, answer deep technical questions, or administer quizzes.

    Args:
        topic: The exact name of the course topic.
        day_number: The specific integer day number to retrieve
    """
    logger.info(msg=f"LLM requested deep-dive content for {topic}, Day {day_number}")
    try:
        db=get_mcp_db()
        clean_topic=topic.replace("_"," ")
        lesson=await db.db.daily_lessons.find_one({
            "course_topic": clean_topic,
            "username": MCP_IDENTITY,
            "day_number": day_number
        })

        if not lesson: 
            return f"No Content found for {clean_topic} on {day_number}. Verify the topic name and day number"
        else:
            content=f"**Module Content: Day {lesson['day_number']} - {lesson['daily_topic']}**\n"
            content+=f"**Core Course Project Context**: {lesson.get('running_use_case_project','N/A')}\n"
            content+=f"{'='*60}\n\n{lesson.get('lesson_content','No Lesson Text available')}\n\n"
            if lesson.get('quiz_content'):
                content+=f"{'='*60}\n{lesson['quiz_content']}"
            
            return content
    except Exception as e:
        return f"Database Error while fetching daily lessons: {str(e)}"


@mcp.resource(uri="khudse://platform/architecture")
def get_khudse_platform_rules():
    """
    Provides the LLM with read-only context about how the Khudse AI Learning Platform operates, so it understands the ecosystem it is interacting with
    """
    logger.info(msg="LLM accessed the Khudse architecture resource.")

    return """
    # Khudse Platform Architecture & Rules

    1. Core Identity: Khudse is an AI-Powered personalized learning platform.
    2. Generation Engine: Courses are generated asynchronously in the background using a Mixture of Agents
    3. Infrastructure:
        - Backend: FastAPI
        - Database: MongoDB (Checkpoints and Daily lessons)
        - Frontend: Streamlit with Asynchronous AI polling
    4. Content Structure: A standard module consists of a comprehensive markdown study guide followed by a daily technical quiz
    5. State Management: The platform uses Langgraph checkpointer state. Content is strictly finalized in the database only after the heavy LLM generation is completely finished.
    """

@mcp.prompt()
def tutor_me(course_topic: str)  -> str:
    """
    Creates a pre-written starting message for the user to launch a strict session for a specific generated course
    """

    return f"""
    I am currently stufying '{course_topic}' on the Khudse platform.

    Please act as a strict, pedagogical tutor.
    1. Use the `get_course_summary` and `get_lesson_deep_dive` tools to read my current curriculum.
    2. Quiz me on the material one question at a time.
    3. Do not give me the answer immediately. If I get it wrong, give me a hing and make me try again 
 
    """

if __name__=="__main__":
    logger.info(msg="Starting FastMCP Server on STDIO...")
    mcp.run()