import random
import string
from locust import HttpUser, task, between

class KhudseLoadTestUser(HttpUser):
    # simulates a user thinking for 1 to 5 seconds between actions
    wait_time=between(min_wait=1, max_wait=5)

    def on_start(self):
        """
        Executes exactly once per Virtual User when they spawn
        Perfectly matches authentication.py router
        """
        # 1. Generate unique credentials to avoid 400 'Username is already Registered' errors
        random_suffix=''.join(random.choices(string.ascii_lowercase+string.digits, k=6))
        self.username=f"testuser_{random_suffix}"
        self.password='LoadTest123!'
        self.email=f"{self.username}@loadtest.com"

        # keep track of topics generated by this specific user
        self.known_topics=[]

        # 2. Registration (matches @router.post("/register"))
        self.client.post(url="/register", json={
            "username":self.username,
            "email": self.email,
            "password": self.password
        },name="1. Register")


        # 3. Authorization (Matches @router.post("/authorize"))
        response=self.client.post(url="/authorize", data={
            "username": self.username,
            "password": self.password
        }, name="2. Authorize")

        if response.status_code==200:
            token=response.json().get("access_token")
            self.client.headers['Authorization']=f"Bearer {token}"
        else:
            print(f"Failed to log in: {response.text}")

    ### FREE TIER TASKS (Database & Traefik Load)
    @task(weight=4)
    def check_dashboard(self):
        """
        Matches @router.get('my-courses')
        """
        response=self.client.get(url="/my-courses", name="3. Get Dashboard")
        if response.status_code==200:
            data=response.json()
            courses=data.get("courses",[])
            if courses: self.known_topics=[course['course_topic'] for course in courses]
    
    @task(weight=3)
    def view_course_details(self):
        """
        Matches @router.get('/courses/{topic}')
        """
        if self.known_topics:
            topic=random.choice(self.known_topics)
            encoded_topic=topic.replace(" ","_")
            self.client.get(
                url=f"/courses/{encoded_topic}",
                name="4. View Course Outline"
                )
    
    @task(weight=3)
    def poll_course_status(self):
        """
        Matches @router.get('/courses/{topic}/status')
        """
        if self.known_topics:
            topic=random.choice(self.known_topics)
            encoded_topic=topic.replace(" ","_")
            self.client.get(
                url=f"/courses/{encoded_topic}/status",
                name="5. Poll UI Status"
                )
    
    @task(weight=4)
    def view_specific_day(self):
        """
        Matches @router.get('/courses/{topic}/day/{day_number}')
        """
        if self.known_topics:
            topic=random.choice(self.known_topics)
            encoded_topic=topic.replace(" ","_")
            self.client.get(
                url=f"/courses/{encoded_topic}/day/1",
                name="6. View Day Content"
            )
    
    ### PAID TIER TASKS (Background Tasks & APIs)
    @task(weight=1)
    def generate_new_course(self):
        """
        Matches @router.post("/generate-course")
        """
        topics_list=[
            'Kubernetes Architecture',
            "FastAPI Microservices",
            "Docker Networking",
            "Prometheus Monitoring"
        ]
        chosen_topic=random.choice(topics_list)

        response=self.client.post(
            url="/generate-course",
            json={
                "topic": chosen_topic,
                "duration_months": 1.0,
                "off_days": ['Monday']
            },
            name="7. Generate Course (PAID API)"
        )
        
        if response.status_code==202:
            if chosen_topic not in self.known_topics:
                self.known_topics.append(chosen_topic) 