apiVersion: v1
kind: Secret
metadata: 
  name: backend-credentials
type: Opaque
stringData:
  MONGO_USERNAME: "radhika0607"
  MONGO_PASSWORD: "OOPWsRw9Z3aEO4ae"
  MONGO_URI: "mongodb+srv://radhika0607:OOPWsRw9Z3aEO4ae@cluster0.jzaphye.mongodb.net/?appName=Cluster0"
  GEMINI_API_KEY: "AIzaSyC5Zrq0W5azxPbdLQSvQ0GGbYauBxqryGQ"
  GOOGLE_API_KEY: "AIzaSyC5Zrq0W5azxPbdLQSvQ0GGbYauBxqryGQ"
  SERPER_API_KEY: "33967ff4b36b4e5835ab069b29ce885107cb8e49"
  BRAVE_SEARCH_API_KEY: "BSAPy_TecztKI1Yeivu-TD8-JP7OR-O"
  JWT_SECRET_KEY: "617bcedde0dc5bc6e05bb4c6f811c0c9d77f440c769f2527ecf41f19cb00a896"
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "120"
  MCP_USER: "ritish0607"
