apiVersion: v1
kind: Namespace
metadata: 
  name: monitoring

---

apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: khudse-backend-monitor
  namespace: kube-system
spec:
  repo: https://prometheus-community.github.io/helm-charts
  chart: kube-prometheus-stack
  targetNamespace: monitoring
  valuesContent: |-

    alertmanager:
      enabled: false
    
    grafana:
      enabled: true
      adminUser: "ritishadhikari"
      adminPassword: "khudsegrafana"

    prometheus:
      prometheusSpec:
        # keep data for only 2 days time period
        retention: 2d
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
