apiVersion: v1
kind: Namespace
metadata: 
  name: monitoring

---

apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: khudse-backend-monitor
  namespace: kube-system
spec:
  repo: https://prometheus-community.github.io/helm-charts
  chart: kube-prometheus-stack
  targetNamespace: monitoring
  valuesContent: |-

    alertmanager:
      enabled: true
      config:
        global:
          resolve_timeout: 5m
          smtp_smarthost: 'smtp.gmail.com:587'
          smtp_from: 'ritishadhikari@gmail.com'
          smtp_auth_username: 'ritishadhikari@gmail.com'
          smpt_auth_password: 'jajrerrwtzphxxul'
        route:
          group_by: ['alertname', 'job']
          group_wait: 30s
          group_interval: 5m  # will send new failures only after 5 minutes
          repeat_interval: 4h
          receiver: 'email-alerts'
        receivers:
        - name: 'email-alerts'
          email_configs:
          - to: 'adhikari_ritish@rediffmail.com'
            send_resolved: true
          - to: 'radhik0607@gmail.com'
            send_resolved: true   
    grafana:
      enabled: true
      admin:
        existingSecret: "grafana-admin-credentials"
        userKey: admin-user
        passwordKey: admin-password

    prometheus:
      prometheusSpec:
        # keep data for only 2 days time period
        retention: 2d
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
