name: Continuous Deployment Pipeline

# triggers the CD pipeline only after the CI pipeline finishes successfully on the main branch
# can survive a terraform destroy and terraform apply. Only config has to be updated in the secret

on:
    workflow_run:
        workflows: ['Continuous Integration Pipeline']
        types:
            - completed
        branches:
            - main

jobs:
    deploy-to-cluster:
        # double checking that the CI run actually passed before attempting to deploy
        if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'}}
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Install Kubectl
              uses: azure/setup-kubectl@v3
              with:
                version: 'latest'

            - name: Authenticate with K3s Cluster
              env: 
                KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
              run: |
                mkdir -p ~/.kube
                echo "$KUBE_CONFIG_DATA" > ~/.kube/config
                chmod 600 ~/.kube/config
            
            - name: Install Bitnami and Inject Master Key
              env:
                BITNAMI_KEY: ${{ secrets.BITNAMI_MASTER_KEY }}
              run: |
                # temporarily save the master key from the secret
                echo "$BITNAMI_KEY" > master-key.yaml

                # only apply the key if it does not already exists to prevent resourceVersion conflicts
                if ! kubectl get secret sealed-secrets-keynfhzm -n kube-system > /dev/null 2>&1; then                   
                  echo "Injecting Bitnami Master Key..."
                  kubectl apply -f master-key.yaml
                else
                  echo "Bitnami Master Key already exists in the cluster. Skipping injection."
                fi

                rm master-key.yaml

                # install the controller which would automatically adopt the key we injected above
                kubectl apply -f https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.27.1/controller.yaml

                # wake up for the controller to wake up before proceeding
                kubectl rollout status deployment/sealed-secrets-controller -n kube-system --timeout=120s
            
            - name: Install Cert-Manager
              run: |
                # Add the official Cert-Manager Helm repository
                helm repo add jetstack https://charts.jetstack.io
                helm repo update

                # Install Cert-Manager into the cluster
                helm upgrade --install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --set installCRDs=true --wait
                
                # applying the certificate issuer first so that it can watch for the ingress sharing the same metadata name as this cert-issuer.yaml
                kubectl apply -f ./k8s_manifests/09-cert-issuer.yaml

            - name: Deploy Core Infrastructure & Helm Engine
              run: |

                # If an old pre canary conflicting frontend ingress is found, then remove them safely

                # Apply everything EXCEPT the ServiceMonitor first
                kubectl apply -f ./k8s_manifests/05-monitoring.yaml
                kubectl apply -f ./k8s_manifests/01-backend_sealed_secrets.yaml
                kubectl apply -f ./k8s_manifests/02-backend_svc_depl.yaml
                kubectl apply -f ./k8s_manifests/03-frontend_svc_depl.yaml
                kubectl apply -f ./k8s_manifests/04-ingress.yaml

                # Apply the new Canary components
                kubectl apply -f ./k8s_manifests/10-canary-backend_svc_depl.yaml
                kubectl apply -f ./k8s_manifests/11-canary-frontend_svc_depl.yaml
                kubectl apply -f ./k8s_manifests/12-canary-routing.yaml
                
            - name: Await Prometheus CRD Initialization
              run: |
                echo "Waiting for K3s Helm Controller to download and install Prometheus CRDs"
                # This loop pings the Kubernetes API every 5 seconds
                # It blocks the pipeline from moving forward until the CRD exists
                while ! kubectl get crd servicemonitors.monitoring.coreos.com > /dev/null 2>&1; do
                  echo "CRDs not ready yet, sleeping 5s..."
                  sleep 5
                done
                echo "Prometheus CRDs are established!"
                # Add a tiny 10s buffer to ensure the API is ready to accept files
                sleep 10
            
            - name: Deploy Service Monitors
              run: |
                kubectl apply -f ./k8s_manifests/06-servicemonitor.yaml
                kubectl apply -f ./k8s_manifests/07-grafana-dashboard.yaml

            - name: Trigger Rolling Updates
              run: |
                # Force the API and Frontend supervisors to pull respective new images
                kubectl rollout restart deployment api
                kubectl rollout restart deployment frontend
                kubectl rollout restart deployment api-canary
                kubectl rollout restart deployment frontend-canary
            
            - name: Verify Deployment Status
              run: |
                kubectl rollout status deployment api
                kubectl rollout status deployment frontend
                kubectl rollout status deployment api-canary
                kubectl rollout status deployment frontend-canary