name: Backend CI Pipeline

on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:

  test-and-verify:
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Inject Environment Variables
        run: |
          touch .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env
          echo "ALGORITHM=${{ secrets.ALGORITHM }}" >> .env
          echo "ACCESS_TOKEN_EXPIRE_MINUTES=${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}" >> .env
          
      - name: Build and Test Docker Compose
        run: docker compose up -d --build 
      
      # Give Mongodb and UviCorn a few seconds to fully boot up
      - name: Wait for Environment Initialization
        run: sleep 15
      
      - name: Execute Pytest
        run: docker exec topic_to_content pytest -v

      - name: Tear Down Containers
        if: always()
        run: docker compose down
          

    
